remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

title: Ralph Services
description: Spaniel Approved Pet Supplies

github:
  is_project_page: false
# include:
 # - assets/css/style.css
