remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Ralph Services
description: Spaniel Approved Pet Supplies

github:
  is_project_page: false
